apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-server-ingress
spec:
  rules:
  - host: data-server.api
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: data-server-service
          servicePort: 8080