apiVersion: v1
kind: Service
metadata:
  name: react-webapp-frontend
spec:
  selector:
    app: react-webapp
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30000