apiVersion: v1
kind: Service
metadata:
  name: react-webapp-service
spec:
  selector:
    app: react-webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3000
      nodePort: 30000