apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp-deployment
  labels:
    app: react-webapp
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: react-webapp
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
      - name: react-webapp
        image: famasboy888/react-webapp:0.0.1.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000